// Lista oficial de objetos de Pokémon Champions v1.0.2
// Fuente: NextN — "Todos los objetos disponibles en Pokémon Champions 1.0.2"
// Incluye nombre ES, nombre en PokeAPI (para sprite), y efecto

export const CHAMPIONS_ITEMS = [

  // ─── Bayas de estado ─────────────────────────────────────────────────────
  { nameES: 'Baya Zreza',   nameAPI: 'cheri-berry',    effect: 'Cura parálisis' },
  { nameES: 'Baya Atania',  nameAPI: 'chesto-berry',   effect: 'Cura sueño' },
  { nameES: 'Baya Meloc',   nameAPI: 'pecha-berry',    effect: 'Cura veneno' },
  { nameES: 'Baya Safre',   nameAPI: 'rawst-berry',    effect: 'Cura quemaduras' },
  { nameES: 'Baya Perasi',  nameAPI: 'aspear-berry',   effect: 'Cura congelamiento' },
  { nameES: 'Baya Zanama',  nameAPI: 'leppa-berry',    effect: 'Recupera 10 PP de un movimiento' },
  { nameES: 'Baya Aranja',  nameAPI: 'oran-berry',     effect: 'Cura 10 PS cuando bajan al 50%' },
  { nameES: 'Baya Caquic',  nameAPI: 'persim-berry',   effect: 'Cura confusión' },
  { nameES: 'Baya Ziuela',  nameAPI: 'lum-berry',      effect: 'Cura todos los problemas de estado' },
  { nameES: 'Baya Zidra',   nameAPI: 'sitrus-berry',   effect: 'Restaura 1/4 PS cuando bajan al 50%' },

  // ─── Bayas resistencia por tipo ──────────────────────────────────────────
  { nameES: 'Baya Caoca',   nameAPI: 'occa-berry',     effect: 'Reduce daño superefectivo fuego ×0.5' },
  { nameES: 'Baya Pasio',   nameAPI: 'passho-berry',   effect: 'Reduce daño superefectivo agua ×0.5' },
  { nameES: 'Baya Gualot',  nameAPI: 'wacan-berry',    effect: 'Reduce daño superefectivo eléctrico ×0.5' },
  { nameES: 'Baya Tamar',   nameAPI: 'rindo-berry',    effect: 'Reduce daño superefectivo planta ×0.5' },
  { nameES: 'Baya Rimoya',  nameAPI: 'yache-berry',    effect: 'Reduce daño superefectivo hielo ×0.5' },
  { nameES: 'Baya Pomaro',  nameAPI: 'chople-berry',   effect: 'Reduce daño superefectivo lucha ×0.5' },
  { nameES: 'Baya Kebia',   nameAPI: 'kebia-berry',    effect: 'Reduce daño superefectivo veneno ×0.5' },
  { nameES: 'Baya Acardo',  nameAPI: 'shuca-berry',    effect: 'Reduce daño superefectivo tierra ×0.5' },
  { nameES: 'Baya Kouba',   nameAPI: 'coba-berry',     effect: 'Reduce daño superefectivo volador ×0.5' },
  { nameES: 'Baya Payapa',  nameAPI: 'payapa-berry',   effect: 'Reduce daño superefectivo psíquico ×0.5' },
  { nameES: 'Baya Yecana',  nameAPI: 'tanga-berry',    effect: 'Reduce daño superefectivo bicho ×0.5' },
  { nameES: 'Baya Alcho',   nameAPI: 'charti-berry',   effect: 'Reduce daño superefectivo roca ×0.5' },
  { nameES: 'Baya Drasi',   nameAPI: 'kasib-berry',    effect: 'Reduce daño superefectivo fantasma ×0.5' },
  { nameES: 'Baya Anjiro',  nameAPI: 'haban-berry',    effect: 'Reduce daño superefectivo dragón ×0.5' },
  { nameES: 'Baya Dillo',   nameAPI: 'colbur-berry',   effect: 'Reduce daño superefectivo siniestro ×0.5' },
  { nameES: 'Baya Baribá',  nameAPI: 'babiri-berry',   effect: 'Reduce daño superefectivo acero ×0.5' },
  { nameES: 'Baya Hibis',   nameAPI: 'roseli-berry',   effect: 'Reduce daño superefectivo hada ×0.5' },
  { nameES: 'Baya Chilan',  nameAPI: 'chilan-berry',   effect: 'Reduce daño recibido tipo normal ×0.5' },

  // ─── Objetos competitivos ─────────────────────────────────────────────────
  { nameES: 'Polvo Brillo',         nameAPI: 'bright-powder',     effect: 'Precisión ataques recibidos −10%' },
  { nameES: 'Hierba Blanca',        nameAPI: 'white-herb',        effect: 'Restaura estadísticas bajadas una vez' },
  { nameES: 'Garra Rápida',         nameAPI: 'quick-claw',        effect: '20% de atacar primero ignorando velocidad' },
  { nameES: 'Hierba Mental',        nameAPI: 'mental-herb',       effect: 'Evita una vez enamoramiento y efectos de control' },
  { nameES: 'Roca del Rey',         nameAPI: 'kings-rock',        effect: '10% de hacer retroceder con ataques' },
  { nameES: 'Polvo Plata',          nameAPI: 'silver-powder',     effect: 'Potencia ataques bicho +20%' },
  { nameES: 'Cinta Aguante',        nameAPI: 'scope-lens',        effect: '10% de sobrevivir con 1 PS a KO' },
  { nameES: 'Periscopio',           nameAPI: 'scope-lens',        effect: 'Probabilidad de crítico 12.5%' },
  { nameES: 'Revestimiento Metálico', nameAPI: 'metal-coat',      effect: 'Potencia ataques acero +20%' },
  { nameES: 'Restos',               nameAPI: 'leftovers',         effect: 'Restaura 1/16 PS cada turno' },
  { nameES: 'Bola Luminosa',        nameAPI: 'light-ball',        effect: 'Duplica ATK y ATK ESP de Pikachu' },
  { nameES: 'Arena Fina',           nameAPI: 'soft-sand',         effect: 'Potencia ataques tierra +20%' },
  { nameES: 'Piedra Dura',          nameAPI: 'hard-stone',        effect: 'Potencia ataques roca +20%' },
  { nameES: 'Semilla Milagro',      nameAPI: 'miracle-seed',      effect: 'Potencia ataques planta +20%' },
  { nameES: 'Gafas de Sol',         nameAPI: 'black-glasses',     effect: 'Potencia ataques siniestro +20%' },
  { nameES: 'Cinturón Negro',       nameAPI: 'black-belt',        effect: 'Potencia ataques lucha +20%' },
  { nameES: 'Imán',                 nameAPI: 'magnet',            effect: 'Potencia ataques eléctrico +20%' },
  { nameES: 'Agua Mística',         nameAPI: 'mystic-water',      effect: 'Potencia ataques agua +20%' },
  { nameES: 'Pico Afilado',         nameAPI: 'sharp-beak',        effect: 'Potencia ataques volador +20%' },
  { nameES: 'Flecha Venenosa',      nameAPI: 'poison-barb',       effect: 'Potencia ataques veneno +20%' },
  { nameES: 'Hielo Perpetuo',       nameAPI: 'never-melt-ice',    effect: 'Potencia ataques hielo +20%' },
  { nameES: 'Hechizo',              nameAPI: 'spell-tag',         effect: 'Potencia ataques fantasma +20%' },
  { nameES: 'Cuchara Torcida',      nameAPI: 'twisted-spoon',     effect: 'Potencia ataques psíquico +20%' },
  { nameES: 'Carbón',               nameAPI: 'charcoal',          effect: 'Potencia ataques fuego +20%' },
  { nameES: 'Colmillo Dragón',      nameAPI: 'dragon-fang',       effect: 'Potencia ataques dragón +20%' },
  { nameES: 'Pañuelo de Seda',      nameAPI: 'silk-scarf',        effect: 'Potencia ataques normal +20%' },
  { nameES: 'Pluma Feérica',        nameAPI: 'fairy-feather',     effect: 'Potencia ataques hada +20%' },
  { nameES: 'Banda Aguante',        nameAPI: 'focus-sash',        effect: 'Sobrevive con 1 PS a KO con PS completos' },
  { nameES: 'Cascabel Concha',      nameAPI: 'shell-bell',        effect: 'Recupera 1/8 del daño infligido' },
  { nameES: 'Pañuelo Elección',     nameAPI: 'choice-scarf',      effect: 'Velocidad +50%, no puedes cambiar de movimiento' },

  // ─── Mega Piedras ─────────────────────────────────────────────────────────
  // Una por cada Pokémon con Mega Evolución disponible en Champions
  // Sprites: nameAPI = '{pokemon}-ite' o nombre específico
  { nameES: 'Venusaurita',    nameAPI: 'venusaurite',     effect: 'Mega Evoluciona a Venusaur' },
  { nameES: 'Charizardita X', nameAPI: 'charizardite-x',  effect: 'Mega Evoluciona a Mega Charizard X' },
  { nameES: 'Charizardita Y', nameAPI: 'charizardite-y',  effect: 'Mega Evoluciona a Mega Charizard Y' },
  { nameES: 'Blastoiseita',   nameAPI: 'blastoisinite',   effect: 'Mega Evoluciona a Blastoise' },
  { nameES: 'Beedrillita',    nameAPI: 'beedrillite',     effect: 'Mega Evoluciona a Beedrill' },
  { nameES: 'Pidgeotita',     nameAPI: 'pidgeotite',      effect: 'Mega Evoluciona a Pidgeot' },
  { nameES: 'Alakazamita',    nameAPI: 'alakazite',       effect: 'Mega Evoluciona a Alakazam' },
  { nameES: 'Machampita',     nameAPI: 'mawilite',        effect: 'Mega Evoluciona a Machamp' },
  { nameES: 'Slowbroita',     nameAPI: 'slowbronite',     effect: 'Mega Evoluciona a Slowbro' },
  { nameES: 'Gengarita',      nameAPI: 'gengarite',       effect: 'Mega Evoluciona a Gengar' },
  { nameES: 'Kangaskhanita',  nameAPI: 'kangaskhanite',   effect: 'Mega Evoluciona a Kangaskhan' },
  { nameES: 'Pinsarita',      nameAPI: 'pinsirite',       effect: 'Mega Evoluciona a Pinsir' },
  { nameES: 'Gyaradosita',    nameAPI: 'gyaradosite',     effect: 'Mega Evoluciona a Gyarados' },
  { nameES: 'Aerodactylita',  nameAPI: 'aerodactylite',   effect: 'Mega Evoluciona a Aerodactyl' },
  { nameES: 'Ampharosita',    nameAPI: 'ampharosite',     effect: 'Mega Evoluciona a Ampharos' },
  { nameES: 'Scizarita',      nameAPI: 'scizorite',       effect: 'Mega Evoluciona a Scizor' },
  { nameES: 'Heracrossita',   nameAPI: 'heracronite',     effect: 'Mega Evoluciona a Heracross' },
  { nameES: 'Houndoomita',    nameAPI: 'houndoominite',   effect: 'Mega Evoluciona a Houndoom' },
  { nameES: 'Tyranitarita',   nameAPI: 'tyranitarite',    effect: 'Mega Evoluciona a Tyranitar' },
  { nameES: 'Gardevoirita',   nameAPI: 'gardevoirite',    effect: 'Mega Evoluciona a Gardevoir' },
  { nameES: 'Sableyeita',     nameAPI: 'sablenite',       effect: 'Mega Evoluciona a Sableye' },
  { nameES: 'Aggronita',      nameAPI: 'aggronite',       effect: 'Mega Evoluciona a Aggron' },
  { nameES: 'Medichamita',    nameAPI: 'medichamite',     effect: 'Mega Evoluciona a Medicham' },
  { nameES: 'Manectricita',   nameAPI: 'manectite',       effect: 'Mega Evoluciona a Manectric' },
  { nameES: 'Sharpeadita',    nameAPI: 'sharpedonite',    effect: 'Mega Evoluciona a Sharpedo' },
  { nameES: 'Cameruptita',    nameAPI: 'cameruptite',     effect: 'Mega Evoluciona a Camerupt' },
  { nameES: 'Altariaita',     nameAPI: 'altarianite',     effect: 'Mega Evoluciona a Altaria' },
  { nameES: 'Banetteita',     nameAPI: 'banettite',       effect: 'Mega Evoluciona a Banette' },
  { nameES: 'Absolita',       nameAPI: 'absolite',        effect: 'Mega Evoluciona a Absol' },
  { nameES: 'Glalieita',      nameAPI: 'glalitite',       effect: 'Mega Evoluciona a Glalie' },
  { nameES: 'Salamencita',    nameAPI: 'salamencite',     effect: 'Mega Evoluciona a Salamence' },
  { nameES: 'Lopunnyita',     nameAPI: 'lopunnite',       effect: 'Mega Evoluciona a Lopunny' },
  { nameES: 'Garchompita',    nameAPI: 'garchompite',     effect: 'Mega Evoluciona a Garchomp' },
  { nameES: 'Lucariota',      nameAPI: 'lucarionite',     effect: 'Mega Evoluciona a Lucario' },
  { nameES: 'Abomasnowita',   nameAPI: 'abomasite',       effect: 'Mega Evoluciona a Abomasnow' },
  { nameES: 'Galladita',      nameAPI: 'galladite',       effect: 'Mega Evoluciona a Gallade' },
  { nameES: 'Audinoita',      nameAPI: 'audinite',        effect: 'Mega Evoluciona a Audino' },
]

// ─── IDs para descarga de sprites ────────────────────────────────────────────
// Sprite URL: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/{nameAPI}.png
export const ITEM_SPRITE_NAMES = CHAMPIONS_ITEMS.map(i => i.nameAPI)
